### ISSUE TITLE
Too many citations

### ISSUE THREAD

**Issue by maximeescande** [justinribeiro/zotero-google-scholar-citation-count#18]
Hi, great plugin :)
But it seems that the citations count shown is about the double of the one on Google Scholar.
An example: 10.1065/lca2007.11.367 (Methodologies for social life cycle assessment) shows 1344 citation as of today (05.10.2023) while on Google Scholar it is 694. (694x2=1388)
Another one: 10.1016/j.jclepro.2020.121506 (Past and future of Social Life Cycle Assessment: Historical evolution and research trends) shows 208 while only 110 on GS (110x2=220).

It is not exactly the double but more than that.

**Comment by kklevine** [comment]
I am having this issue with a number or citations I'm looking at. Take 10.1016/j.trc.2020.102640 for example, GSCC is retrieving 108 citations, but GS shows only 55. 

The example with the biggest error is "California’s Freeway Service Patrol Program: Management Information System Annual Report Fiscal Year 2019-20" https://escholarship.org/uc/item/0d3969cd which GSCC retrieves 0010763 citations, but GS has 0. 

Going through my corpus it was hard to determine which items were incorrect or not, or if there was a pattern.

**Comment by justinribeiro** [comment]
If you're looking for a _definitive_ number of citations for a given resource, Google Scholar is not the tool for that usage. GS has known issues with this (it'll report wildly in some cases, see https://fediscience.org/@ct_bergstrom/111303567826479298 for one such case).

The plugin does its best to try to use what Google Scholar returns a guidepost and nothing more. There isn't much I can do plugin-wise to resolve this without using making it very very opinionated (which I have tried to keep in check, because that has it's own problems for maintenance and viability).

**Comment by kklevine** [comment]
That makes sense! GS is what it is. I will try to figure out how to work with these results - being mindful of potential errors. 

I really appreciate your work on this plugin and its ability to help me try to tell the story of impact with grey lit. Thank you!
