### ISSUE TITLE
Does anyone know why there is this prompt?

### ISSUE THREAD

**Issue by Panyidan** [justinribeiro/zotero-google-scholar-citation-count#27]
![image](https://github.com/user-attachments/assets/5c8ba713-2d1b-4a67-b8fb-ce768b666d62)

Please enter the Captcha on the page that will now open and then re-try updating the citations, or wait a while to get unblocked by Google if the Captcha is not present.

**Comment by justinribeiro** [comment]
This happens when Google Scholar doesn't come back with a 200 response (e.g., it thinks you are a robot). This is a limitation of GS because they don't offer a pure API (the whole thing is built on working around this) and depending on your IP address can be an issue (I get locked out during testing...and then you have to just wait for the IP ban to lift).

When this message pops up, you should get another screen asking for the recaptcha which then you complete will let it continue to work (most of the time... Sometimes GS is stubborn)
