### ISSUE TITLE
Hope to remove <sub> or </sub> before search

### ISSUE THREAD

**Issue by pencilheart** [justinribeiro/zotero-google-scholar-citation-count#35]
Superscripts and subscripts in entry titles should be standardized in Zotero, therefore, the title of 
《(Y<sub>0.25</sub>Yb<sub>0.25</sub>Er<sub>0.25</sub>Lu<sub>0.25</sub>)<sub>2</sub>(Zr<sub>0.5</sub>Hf<sub>0.5</sub>)<sub>2</sub>O<sub>7</sub>: a defective fluorite structured high entropy ceramic with low thermal conductivity and close thermal expansion coefficient to Al<sub>2</sub>O<sub>3</sub>》
should be revised to
`(Y<sub>0.25</sub>Yb<sub>0.25</sub>Er<sub>0.25</sub>Lu<sub>0.25</sub>)<sub>2</sub>(Zr<sub>0.5</sub>Hf<sub>0.5</sub>)<sub>2</sub>O<sub>7</sub>: a defective fluorite structured high entropy ceramic with low thermal conductivity and close thermal expansion coefficient to Al<sub>2</sub>O<sub>3</sub>`.

However, this revised title can not be searched in Google Scholar, the `<sub>` or `</sub>` should be removed before searching.

So, can you set detect `<sub>` or `</sub>` in the title and remove them before searching?

Thanks.

**Comment by justinribeiro** [comment]
So I've been trying to duplicate the behavior from Zotero using that paper, and I'm curious how you get a html in the title? The raw PDF reindex won't inject HTML, nor will the web site connector pull. 
![image](https://github.com/user-attachments/assets/a607e044-d298-4259-8924-b424b1ecae39)
Is this a case of manual title edit to add html?

I ask because while I am very appreciative of the PR, it's very specific to a single case; given HTML could be in the string (which, I hadn't considered in Zotero), I could generalize more using `DOMParser().parseFromString()` and extract that concern into it's own function to validate and test (as I might stick it behind a preference since I'm not 100% certain as to the impact overall).

Let me give this some thought today. :+1:

**Comment by pencilheart** [comment]
Thanks for your consider!

The addon [Linter for Zotero](https://github.com/northword/zotero-format-metadata) can manual edit title through the toolbox above info panel.
<img width="1350" alt="Xnip2024-11-22_10-26-20" src="https://github.com/user-attachments/assets/d6c8a911-8182-487a-9200-8a003c60a915">

Then the title in main interface will be formatted, meanwhile the reference in Microsoft Word will also be formatted.

<img width="688" alt="Xnip2024-11-22_10-25-10" src="https://github.com/user-attachments/assets/af4af688-f335-42e6-a57a-099ad8d61fc7">


Yes, keep it in perference is a good idea. I don't really know how many people using this addon like this way. I use this HTML because some journals and my thesis must format the superscript and subscript in title.

Appreciate your addon again❤️
